### ISSUE TITLE
Passing multiline markdown notes to stories

### ISSUE THREAD

**Issue by gorkamolero** [mattrothenberg/vue-storybook#10]
Hi!

Great work on the plugin. I'd like to know if I can pass data dinamically to the notes attribute. This will work:

```
<story ... notes="# Line 1
  ### Line 2
  Line 3">
```

However, it's not ideal. How could I achieve this, passing some variable to the story tag?

**Comment by mattrothenberg** [comment]
Hi @gorkamolero,

As far as I know, this isn't possible since the `<story>` blocks are parsed as strings. You can always register the stories manually (via `storiesOf`) if you need this extra granularity.

Hope that helps

**Comment by gorkamolero** [comment]
Oh, dear

Can you think of any way to achieve this? I'd be happy to spend some dev time working on this, but I wouldn't know where to start.

Thanks again

**Comment by mattrothenberg** [comment]
Personally I think this is a deliberate limitation of the `vue-storybook` approach, and perhaps an indication that you should be using the normal Storybook API for registering stories with verbose notes/textual information. 

That said, you can always clone my repo (be sure to use the `v2` branch) and develop locally with it using `yarn link.`
