### ISSUE TITLE
How can I pass emitted values to an action?

### ISSUE THREAD

**Issue by Emobe** [mattrothenberg/vue-storybook#15]
I see in the example, it shows `@click="action('show me the money', isDisabled)"` as a way to use actions. Though this takes the value from the knobs, rather than the event itself. I'm not sure why you would need to pass a knob value to an action as it should be handled "internally" and eventually emitted if so.

How can I use actions like `@click="action('clicked')` where the action will have the value emitted from the event passed to it and the action output would be like `clicked: MouseEvent`, like how its used within storybook itself?

**Comment by mattrothenberg** [comment]
Good question. I remember having trouble with this particular use-case but can't quite recall the details.

https://github.com/mattrothenberg/vue-storybook/blob/master/src/register.js#L26-L33 might be a good place to start if you want to debug and submit a PR!

Cheers,
Matt

**Comment by Emobe** [comment]
Thanks, I shall take a look. Glad to know that I wasn't just going crazy

**Comment by Emobe** [comment]
Okay so from what I can see, the action's handler is currently being directly called like `action(name)(...payload)`, where usually the handler will be called when the event has been emitted. Did it have something to do with the action's "handler" not being processed correctly or getting "lost" once it has been parsed through the plugin?

**Comment by mattrothenberg** [comment]
I believe so, yep.

Feel free to `yarn link` that repo locally and point a storybook project at it. You should have a pretty fast feedback loop there for debugging.

**Comment by Emobe** [comment]
Cool, wanted to make sure I was on the right track. Will look into this more.

**Comment by mattrothenberg** [comment]
@Emobe closing this. Looking forward to your PR.
