### ISSUE TITLE
Possible to use require.context to automatically register stories?

### ISSUE THREAD

**Issue by chrisvfritz** [mattrothenberg/vue-storybook#3]
In the current example, it looks like every `.vue` file must be manually imported once a `<story>` block is added. I think ideally, adding a `<story>` block would automatically register the story. Could this be achieved with Webpack's [`require.context`](https://webpack.js.org/guides/dependency-management/#require-context), similar to how it's sometimes used to automatically register [base components](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/src/components/_globals.js) or [Vuex modules](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/src/state/modules/index.js)?

**Comment by mattrothenberg** [comment]
Ooh, this is an awesome idea!

I haven't explored `require.context` yet, but I'm happy to give it a shot (I also welcome PRs with a virtual hug and/or a coffee/beer 😉)



(Did I just bribe you?)

**Comment by chrisvfritz** [comment]
Ha, I _do_ take bribes and am indeed a hugger, 🤗 but it may take me a little while to get to a PR which is why I figured I'd open an issue first. Btw, it looks like there might be an [official Storybook plugin](https://twitter.com/NorbertdeLangen/status/981523178378973184) for Vue CLI that uses your loader. 🙂

**Comment by mattrothenberg** [comment]
Whoa, that's good news!

I'll definitely take a swing at this when I find some free time.

**Comment by mattrothenberg** [comment]
@chrisvfritz Et voilà a pull request for your consideration (at yr convenience, of course)

https://github.com/mattrothenberg/vue-storybook/pull/4

**Comment by mattrothenberg** [comment]
@chrisvfritz Give `0.3.0` a whirl! https://github.com/mattrothenberg/vue-storybook/releases/tag/v0.3.0

Here's a sample repo for experimentation: https://github.com/mattrothenberg/vue-storybook-example
